### PR TITLE
Address issue #44

### PR DESCRIPTION
**Pull request by BenSandeen**
This is my first open source PR, so please keep any criticism constructive, thanks!

### CODE REVIEW

**Comment by BenSandeen** [comment]
> 
> 
> Thanks for the PR!
> 
> I'd rather like a solution which uses `&codebooks.get()` and a if let.

Hopefully this is something like what you have in mind.

**Comment by est31** [comment]
I had more something like this in mind: https://github.com/RustAudio/lewton/blob/0d13bc4a774868d4e55a56568b51339367fb0584/src/audio.rs#L609-L613

**Comment by est31** [comment]
@BenSandeen want to change it? Then I can merge the PR :)

**Comment by BenSandeen** [comment]
Yep, I'll get to work now, sorry for the delay, I've been busy.  Hopefully the third time's the charm! :D

**Comment by BenSandeen** [comment]
And I might as well ask now before pushing another commit: I imagine that, instead of a `break` like in the `else` block of that code snippet, you want to return `Err(FloorSpecialCase::PacketUndecodable)`?

**Comment by est31** [comment]
Yes, that's what I originally imagined.

Actually I think an even better way of fixing the bug would be to reject the entire stream already during header decoding.

For this, please edit the `read_floor` function in header.rs to check any items in `floor0_book_list` for whether they are above `codebook_cnt`. It's mentioned [in the spec](https://www.xiph.org/vorbis/doc/Vorbis_I_spec.html#x1-930006.2.1) but we didn't implement it :/.

Sorry for the back & forth, but I think that's what's most compliant with the spec.

**Comment by est31** [comment]
Specifically, there is a similar check with `codebook_cnt` already below in the function.

**Comment by BenSandeen** [comment]
K, I'll take a look at that

**Comment by BenSandeen** [comment]
All right, I undid the previous changes and made the fix in `header.rs`.  If you prefer, I can kill this PR and make a clean PR without the previous changes I've made in the commit history

**Pull request merged**
