### PR TITLE
Simplify `dual_mut_idx`

### PR DESCRIPTION
**Pull request by AnthonyMikh**
Use inherent methods to get access to mutable elements.

### CODE REVIEW

**Comment by AnthonyMikh** [comment]
Okay, inclusive ranges were introduced in Rust 1.26.0. Should I remake this to use exclusive ranges instead?

**Comment by est31** [comment]
> Should I remake this to use exclusive ranges instead?

@AnthonyMikh that would be helpful, yeah!

**Comment by AnthonyMikh** [comment]
Done. I suppose it worths mentioning in README that the minimal supported Rust version for lewton is 1.20.0.

**Comment by est31** [comment]
@AnthonyMikh it is mentioned!

**Comment by AnthonyMikh** [comment]
> @AnthonyMikh it is mentioned!

Ah, sorry, I misread it.

**Comment by est31** [comment]
Umm could you remove your last commit?

**Comment by est31** [comment]
NVM, merged as 45c3a82dd0a763e85f225a53c5390b23ccf1b6f2

**Pull request closed without merging**
