### PR TITLE
Avoid allocating a vector in loop in `read_audio_packet_generic`

### PR DESCRIPTION
**Pull request by AnthonyMikh**
Fixes a TODO in code

### CODE REVIEW

**Comment by est31** [comment]
Thanks but it's still a copy. The comment should remain.

**Comment by AnthonyMikh** [comment]
Well, at least it avoids allocating a `Vec` in loop.

**Comment by est31** [comment]
That isn't avoided either, because empty vec's don't allocate. But I'll merge it because it saves a line.

**Comment by Luni-4** [comment]
@est31 @AnthonyMikh 

Could [copy_from_slice](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_from_slice) solve the problem? 

Something like this:
```
let vec_at_ch = &vectors[resid_vec_len * ch .. resid_vec_len * (ch + 1)];
residue_vectors[j].copy_from_slice(vec_at_ch);
```

**Comment by est31** [comment]
`copy_from_slice` would still do a copy. You'd also have to 0-initialize the vec meaning an additional step, which makes `extend_from_slice` better.

**Comment by Luni-4** [comment]
> `copy_from_slice` would still do a copy. You'd also have to 0-initialize the vec meaning an additional step, which makes `extend_from_slice` better.

Oh, just looked at the entire code and saw that `residue_vectors` isn't allocated, I thought it was. Disregard my comment then :)

**Pull request merged**
